version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: secret
      MONGO_DATABASE: my-travel-mongo.db
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=my_travel_mysql
      - MYSQL_USER=my_travel
      - MYSQL_PASSWORD=secret
    volumes:
      - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
      - my_travel_mysql_data_container:/var/lib/mysql
    ports:
      - 33069:3306
  nest:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/my-travel
    ports:
      - 3007:3000
    links:
      - mysql
      - mongo

volumes:
  my_travel_mysql_data_container:
