version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: secret
      MONGO_DATABASE: travel-mongo.db
  database:
    image: postgres
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: travel.db
    ports:
      - 55495:5432
  nest:
    build: .
    volumes:
      - .:/travel-app
    ports:
      - 3000:3000
#      - 9229:9229
    depends_on:
      - database
